In [1]:
print("hello world")

hello world


In [ ]:
import numpy as np #to import the numpy library and name it as np 

list vs numpy - time taken

In [3]:
from time import process_time

time taken by a list 
Process_time() function finds the time to complete the range 


In [9]:
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time() #process_time function finds the time taken to complete the range 
python_list= [i+5 for i in python_list] #adding the value 5
end_time= process_time()
print(end_time- start_time )

0.0


In [16]:

from time import process_time
import numpy as np

# Create a NumPy array
np_array = np.array([i for i in range(10000)])

# Start timer
start_time = process_time()

# Add 5 to every element
np_array += 5

# End timer
end_time = process_time()

# Print CPU time taken
print("Time taken:", end_time - start_time, "seconds")


Time taken: 0.0 seconds


numpy array


In [1]:
list =[1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [3]:
import numpy as np
np_list=np.array([1,2,3,4,5]);
print(np_list)
type(np_list)

[1 2 3 4 5]


numpy.ndarray

In [4]:
a=np.array([1,2,3,4,5])
print(a)
a.shape
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


(2, 3)

In [5]:
c=np.array([[1,2,3],[4,5,6]],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


intital placeholders in numpy arrays 
#create a numpy arrays of zeroes

In [8]:
import numpy as np
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


#create a numpy arrays of ones 


In [9]:
y=np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((2,3),100)  #fill the matrix with the same values like here 100
print(z)

[[100 100 100]
 [100 100 100]]


In [ ]:
#create an identity matrix
a=np.eye(3) #fill the diagonal with 1s and rest with 0s
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
b=np.random.random((3,4));
print(b)

[[0.4478186  0.93562889 0.48510465 0.31226489]
 [0.41561185 0.59558741 0.22843189 0.96542325]
 [0.61222041 0.13478217 0.38277915 0.90763254]]


In [4]:
#random value array
import numpy as np
c=np.random.randint(10,100,(3,5))
print(c)


[[56 37 57 15 85]
 [92 88 89 59 97]
 [99 73 11 66 48]]


In [ ]:
#array of evenly spaces values 
import numpy as np
d=np.linspace(10,30,5)#here how many values you want
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaces values ---> specifying the steps
import numpy as np
e=np.arange(10,30,5) #here the gap you want between 2 numbers
print(e)

[10 15 20 25]


In [8]:
#convert a list to an numpy array
import numpy as np 

list2=[10,20,30,40,50]
np_array=np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [10]:
#analying an numpy array
c=np.random.randint(10,90,(2,3))
print(c)
print(c.shape)

[[85 71 71]
 [64 74 78]]
(2, 3)


In [11]:
#number of dimensions 
print(c.ndim)

2


In [12]:
#checking the data type of the value in the array 
print(c.dtype)

int32


MATHEMATICAL OPERATIONS ON THE NUMPY ARRAY

In [17]:
#mathematical operations on the numpy array 

#joining the two lists
list1=[10,20,30,40,50]
list2=[60,70,80,90,100]
print(list1 + list2)


#these are numpy arrays 
import numpy as np
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))
print(a + b)
print(a-b)
print(a*b)


[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[[ 9  3  5]
 [ 2  7 14]
 [ 8 12  6]]
[[ 3  1 -1]
 [ 0 -3 -4]
 [ 6  0  0]]
[[18  2  6]
 [ 1 10 45]
 [ 7 36  9]]


In [19]:
print(np.subtract(a,b))
print(np.add(a,b))
print(np.multiply(a,b))

print(np.divide(a,b))


[[ 3  1 -1]
 [ 0 -3 -4]
 [ 6  0  0]]
[[ 9  3  5]
 [ 2  7 14]
 [ 8 12  6]]
[[18  2  6]
 [ 1 10 45]
 [ 7 36  9]]
[[2.         2.         0.66666667]
 [1.         0.4        0.55555556]
 [7.         1.         1.        ]]


ARRAY MANIPULATION


In [20]:
ar=np.random.randint(0,10,(3,3))
print(ar)
print(ar.shape)

[[4 4 1]
 [4 9 9]
 [7 5 9]]
(3, 3)


In [22]:
#transpose of the matrix
trans=np.transpose(ar)
print(trans)
print(trans.shape)

[[4 4 7]
 [4 9 5]
 [1 9 9]]
(3, 3)


In [27]:
a = np.random.randint(0, 10, (2, 2))
print(a)
print(a.shape)
b = a.reshape(2, 2)
print(b)

[[1 6]
 [0 4]]
(2, 2)
[[1 6]
 [0 4]]


CREATING ARRAYS

In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


TWO DIMENSIONAL ARRAY


In [4]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(arr)

[[10 20]
 [30 40]]


SPECIAL ARRAYS


In [6]:
np.zeros((2,3))
np.ones((2,3))
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

EVENLY SPACES NUMBERS 


In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

ARRAY ATTRIBUTES 


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(2, 4)
8
int64
2


INDEXING 


In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,0])
print(arr[0,1:3])

1
[2 3]


SLICING 


In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1:3])

[2 3]


RESHAPING OF THE ARRAY 


In [12]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


AGGREGATE FUNCTIONS


In [14]:
arr=np.array([1,2,3,4,5,6,7,8])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))


36
4.5
2.29128784747792
8
1


AXIS OPERATIONS


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))


[ 6  8 10 12]
[10 26]
