In [1]:
print("hello world")

hello world


In [ ]:
import numpy as np #to import the numpy library and name it as np 

list vs numpy - time taken

In [3]:
from time import process_time

time taken by a list 
Process_time() function finds the time to complete the range 


In [9]:
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time() #process_time function finds the time taken to complete the range 
python_list= [i+5 for i in python_list] #adding the value 5
end_time= process_time()
print(end_time- start_time )

0.0


In [16]:

from time import process_time
import numpy as np

# Create a NumPy array
np_array = np.array([i for i in range(10000)])

# Start timer
start_time = process_time()

# Add 5 to every element
np_array += 5

# End timer
end_time = process_time()

# Print CPU time taken
print("Time taken:", end_time - start_time, "seconds")


Time taken: 0.0 seconds


numpy array


In [1]:
list =[1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [3]:
import numpy as np
np_list=np.array([1,2,3,4,5]);
print(np_list)
type(np_list)

[1 2 3 4 5]


numpy.ndarray

In [4]:
a=np.array([1,2,3,4,5])
print(a)
a.shape
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


(2, 3)

In [5]:
c=np.array([[1,2,3],[4,5,6]],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


intital placeholders in numpy arrays 
#create a numpy arrays of zeroes

In [8]:
import numpy as np
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


#create a numpy arrays of ones 


In [9]:
y=np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((2,3),100)  #fill the matrix with the same values like here 100
print(z)

[[100 100 100]
 [100 100 100]]


In [ ]:
#create an identity matrix
a=np.eye(3) #fill the diagonal with 1s and rest with 0s
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
